name: Pester
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
jobs:
  pester-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: pester
        shell: pwsh
        run: |
          Import-Module Pester -Force
          $config = [PesterConfiguration]@{
            Run = @{ 
              PassThru = $true 
            }
            CodeCoverage = @{ 
              Enabled = $true
              OutputPath = "ci-cd/coverage.xml"
            }
            TestResult = @{
              Enabled = $true
              OutputPath = "ci-cd/testResults.xml"
            }
          }
          Invoke-Pester -Configuration $config
    
      - name: codecov       
        uses: codecov/codecov-action@v1.0.13
        with:
          name: BuildName
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ci-cd/coverage.xml
