name: Pester
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
jobs:
  pester-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Run Pester tests (pwsh)
      run: |
        Import-Module Pester -Force
        $config = [PesterConfiguration]@{
          Run = @{ 
            PassThru = $true 
          }
          CodeCoverage = @{ 
            Enabled = $true
          }
          TestResult = @{
            Enabled = $true
          }
        }
        Invoke-Pester -Configuration $config
      shell: pwsh
